# Generated by Django 3.2.9 on 2021-11-28 02:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('container_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='[0-9a-fA-F]{64}')])),
                ('timeout_secs', models.FloatField(blank=True, null=True)),
                ('host_start_time_secs', models.FloatField(default=0.0)),
                ('uptime_secs', models.FloatField(default=0.0)),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Timed Out'), (3, 'Docker Error'), (4, 'Not Found'), (5, 'Finished'), (6, 'Failed To Start'), (7, 'Cancelled')], default=0)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastci.job')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastci.pipeline')),
            ],
        ),
    ]
