# Generated by Django 3.2.9 on 2021-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parent',
        ),
        migrations.AddField(
            model_name='job',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_fastci_job_parents_+', to='fastci.Job'),
        ),
    ]
