# Generated by Django 3.2.9 on 2021-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0004_pipeline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Timed Out'), (3, 'Docker Error'), (4, 'Not Found'), (5, 'Finished'), (6, 'Failed To Start'), (7, 'Cancelled'), (8, 'Dependency Failed')], default=0),
        ),
    ]
