# Generated by Django 3.2.9 on 2021-12-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0005_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='fastci.pipeline'),
        ),
    ]
