# Generated by Django 4.0.1 on 2022-01-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0006_alter_job_pipeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-pk']},
        ),
    ]
