# Generated by Django 4.0.1 on 2022-01-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0007_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-pk']},
        ),
    ]
