# Generated by Django 4.0.1 on 2022-01-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0008_alter_pipeline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='tmp_dir',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
