# Generated by Django 4.0.1 on 2022-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0009_pipeline_tmp_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='cleaned_up',
            field=models.BooleanField(default=False),
        ),
    ]
