# Generated by Django 4.0.1 on 2022-01-12 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastci', '0011_alter_job_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='commit_hash',
            field=models.CharField(max_length=40, null=True, validators=[django.core.validators.RegexValidator(regex='[0-9a-fA-F]{40}')]),
        ),
    ]
